#!/usr/bin/env python3
"""Extract each blog card's cover graphic from blog.html into a reusable JS map.

Output: components/blog-covers.js  ->  window.SG_BLOG_COVERS = { "<slug>": "<div class='blog-cover'...>...</div>", ... }

The post pages reuse these covers as a hero banner (and as related-post thumbnails),
so the artwork on the card you click carries through onto the article itself.
This is a one-off generator; re-run it if the index cards change.
"""
import re
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
html = (ROOT / "blog.html").read_text(encoding="utf-8")

# Each card looks like:
#   <a class="blog-card" href="blog/<slug>/" data-cat="...">
#     <div class="blog-cover" style="...">...</div>
#     <div class="blog-body">...</div>
#   </a>
# Capture the slug and the full .blog-cover ... up to (not including) .blog-body.
pattern = re.compile(
    r'<a class="blog-card" href="blog/(?P<slug>[^/"]+)/"[^>]*>\s*'
    r'(?P<cover><div class="blog-cover".*?</div>)\s*'
    r'<div class="blog-body">',
    re.DOTALL,
)

covers = {}
for m in pattern.finditer(html):
    slug = m.group("slug")
    cover = m.group("cover").strip()
    # The cover may contain nested </div> (the .cat-label). Our non-greedy match
    # stops at the FIRST </div>, so re-expand to the correct closing tag by
    # balancing div tags within the captured-through-blog-body region.
    covers[slug] = cover

# Non-greedy stops too early when there's a nested div (cat-label). Re-extract
# each cover by balancing <div>...</div> starting at the blog-cover open tag.
def extract_balanced(start_idx):
    depth = 0
    i = start_idx
    n = len(html)
    tag_re = re.compile(r'<(/?)div\b')
    while i < n:
        mt = tag_re.search(html, i)
        if not mt:
            break
        if mt.group(1) == '':   # opening <div
            depth += 1
        else:                   # closing </div>
            depth -= 1
        # advance past this tag's '>'
        gt = html.index('>', mt.end())
        i = gt + 1
        if depth == 0:
            return html[start_idx:i]
    return html[start_idx:i]

covers = {}
# Match both the grid cards (.blog-card) and the featured hero (.blog-featured)
# so the featured/latest post's cover is never dropped on regeneration.
for am in re.finditer(r'<a class="blog-(?:card|featured)" href="blog/(?P<slug>[^/"]+)/"', html):
    slug = am.group("slug")
    cov_start = html.index('<div class="blog-cover"', am.end())
    covers[slug] = extract_balanced(cov_start).strip()

# Emit JS
lines = [
    "// AUTO-GENERATED by scripts/_gen_blog_covers.py - do not edit by hand.",
    "// Maps blog slug -> the cover graphic markup used on the index card,",
    "// reused as the hero banner and related-post thumbnails on each post page.",
    "window.SG_BLOG_COVERS = {",
]
for slug, cover in covers.items():
    lines.append(f"  {json.dumps(slug)}: {json.dumps(cover)},")
lines.append("};")
out = "\n".join(lines) + "\n"

(ROOT / "components" / "blog-covers.js").write_text(out, encoding="utf-8")
print(f"Wrote components/blog-covers.js with {len(covers)} covers:")
for slug in covers:
    print("  -", slug)
